# Site settings
title: Brendan Horng
description:
favicon: https://i.imgur.com/ra4cJX4.png
baseurl: /Resume
url: http://ludusamo.github.io
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Brendan Horng
  title: Software Developer
  address: New Jersey, US
  email: brendan.horng@ludusamo.com
  link: ludusamo.com
  weibo:
  github: Ludusamo
  linkedin: Brendan-Horng
  twitter: Ludusamo
  gavatar: https://i.imgur.com/ra4cJX4.png
  projectHistory:
    - project1:
      name: Toy Language
      started: 2014
      duration: (May 2015-Present)
      team:
        - member1:
          name: Brendan Horng
      website: https://github.com/Ludusamo/Toy-Language
      description: Small scripting language being developed in C (C99 standard).
    - project2:
      name: Locating and Identifying Viable Asteroids
      started: 2014
      duration: (May 2014-November 2015)
      team:
        - member1:
          name: Brendan Horng
        - member2:
          name: Daniel Gu
        - member3:
          name: Evan Shi
        - member4:
          name: Justin Shetty
        - member5:
          name: Nina Arcot
      website: https://github.com/Ludusamo/Asteroid-Project
      description: Completed for the NASA Epic Challenge. The team created a system capable of being sent to asteroids to determine potential for water content.
  workHistory:
    - work5:
      company: Kynex, Inc (Fair Lawn, New Jersey)
      title: Software Development Intern
      started: 2017
      duration: (2017 - 2017)
      description: Ported an intranet application/toolset from classic ASP to Microsoft C# MVC platform. Developed a new FIX (Financial Information Exchange) Engine for Kynex in C#.
    - work4:
      company: Escape the Room NYC
      location: New York, US
      title: Software Developer
      started: 2016
      duration: (2016 - 2017)
      description: Work on Unity Application for interactive components of an escape the room game. Work closely with puzzle designers to link physical components of the room to present an immersive digital component.
    - work3:
      company: Zaniac
      location: New York, US
      title: Instructor
      started: 2016
      duration: (2016 - 2017)
      description: Zaniac is a K-8, after-school learning facility that inspires young children to learn math and technology. Courses have an emphasis in Science, Technology, Engineering, and Math (STEM).
    - work2:
      company: BrightLogic
      location: New Jersey, US
      title: Software Development Intern
      started: 2015
      duration: (2015 - 2016)
      description: Worked as an intern at BrightLogic and assisted in creating applications for their ActiveFloor product. Application construction is done primarily in Unity.
    - work1:
      company: Academy After Hours
      location: New Jersey, US
      title: Assistant Instructor
      started: 2013
      duration: (2013 - 2013)
      description: Taught classes in Non-Routine Problem Solving and Robotics. Worked with students spanning from grades 1-8. Taught basic programming. Organized class plans.
  educationHistory:
    - education1:
      organization: New York University Tandon School of Engineering
      degree: Bachelor's Science Degree
      major: Computer Science
      started: 2016
      duration: (2016 - Present)
      description: Current student at Tandon School of Engineering in Brooklyn, New York.
    - education2:
      organization: Bergen County Academies
      degree: Highschool
      major: Software Engineering
      started: 2012
      duration: (2012 - 2016)
      description:  Education in the Academy for the Advancement of Technology. Conducted research.
  languages:
    - language1:
      name: Chinese
      proficiency: Conversational
    - language2:
      name: English
      proficiency: Native
  technologySkills:
    - skill1:
      name: C/C++
      percentage: 100%
    - skill2:
      name: Java
      percentage: 100%
    - skill3:
      name: Unity
      percentage: 85%
    - skill4:
      name: Python
      percentage: 80%
    - skill5:
      name: Web Development
      percentage: 95%
    - skill6:
      name: Microsoft Office Suite
      percentage: 100%
    - skill7:
      name: Linux BASH Scripting
      percentage: 90%
    - skill8:
      name: C#
      percentage: 90%
