# Site settings
title: Brendan Horng
description:
favicon: /assets/img/logoV2Thumb.png
baseurl: /Personal-Website
url: http://ludusamo.com
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Brendan Horng
  title: Software Developer
  address: New Jersey, US
  email: brendan.horng@ludusamo.com
  link: brendan.horng.ludusamo.com
  weibo:
  github: Ludusamo
  linkedin: Brendan-Horng
  twitter: Ludusamo
  gavatar: /assets/img/logoV2Thumb.png
  projectHistory:
    - project1:
      name: Locating and Identifying Viable Asteroids
      started: 2014
      team:
        - member1:
          name: Brendan Horng
        - member2:
          name: Daniel Gu
        - member3:
          name: Evan Shi
        - member4:
          name: Justin Shetty
        - member5:
          name: Nina Arcot
      website: https://github.com/Ludusamo/Asteroid-Project
      description: Completed for the NASA Epic Challenge. The team created a system capable of being sent to asteroids to determine potential for water content.
  workHistory:
    - work1:
      company: BrightLogic
      location: New Jersey, US
      title: Intern
      started: 2015
      duration: (2015 - Present)
      description: Worked as an intern. 
  educationHistory:
    - education1:
      organization: Bergen County Academies
      degree: Highschool
      major: Software Engineering
      started: 2012
      duration: (2012 - Present)
      description:  Education in the Academy for the Advancement of Technology. Conducted research.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Spanish
      proficiency: Conversational
  programmingSkills:
    - skill1:
      name: C++
      percentage: 100%
    - skill2:
      name: C
      percentage: 80%
    - skill3:
      name: Java
      percentage: 90%
    - skill4:
      name: Unity
      percentage: 80%
    - skill5:
      name: Java/Java EE
      percentage: 90%
