# Site settings
title: Brendan Horng
description:
favicon: http://imgur.com/itAvIo8.png
baseurl: /Resume
url: http://ludusamo.github.io
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Brendan Horng
  title: Software Developer
  address: New Jersey, US
  email: brendan.horng@ludusamo.com
  link: ludusamo.com
  weibo:
  github: Ludusamo
  linkedin: Brendan-Horng
  twitter: Ludusamo
  gavatar: http://imgur.com/itAvIo8.png
  projectHistory:
    - project1:
      name: Locating and Identifying Viable Asteroids
      started: 2014
      team:
        - member1:
          name: Brendan Horng
        - member2:
          name: Daniel Gu
        - member3:
          name: Evan Shi
        - member4:
          name: Justin Shetty
        - member5:
          name: Nina Arcot
      website: https://github.com/Ludusamo/Asteroid-Project
      description: Completed for the NASA Epic Challenge. The team created a system capable of being sent to asteroids to determine potential for water content.
  workHistory:
    - work1:
      company: BrightLogic
      location: New Jersey, US
      title: Intern
      started: 2015
      duration: (2015 - Present)
      description: Worked as an intern. 
    - work2:
      company: Academy After Hours
      location: New Jersey, US
      title: Assistant Instructor
      started: 2013
      duration: (2013 - 2013)
      description: Taught classes in Non-Routine Problem Solving and Robotics. Worked with students spanning from grades 1-8. Taught basic programming. Organized class plans.
  educationHistory:
    - education1:
      organization: Bergen County Academies
      degree: Highschool
      major: Software Engineering
      started: 2012
      duration: (2012 - Present)
      description:  Education in the Academy for the Advancement of Technology. Conducted research.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Spanish
      proficiency: Conversational
  programmingSkills:
    - skill1:
      name: C/C++
      percentage: 100%
    - skill2:
      name: Java
      percentage: 100%
    - skill3:
      name: Unity
      percentage: 85%
    - skill4:
      name: Python
      percentage: 80%
    - skill5:
      name: Web Development
      percentage: 70%
    - skill6:
      name: Microsoft Office Suite
      percentage: 100%
    - skill7:
      name: Linux BASH Scripting
      percentage: 90%
